name: Linting

on:
  push:
    branches: -dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pylint
      - name: Run linter
        run: |
            pylint $(git ls-files '*.py')
